### ISSUE TITLE
github action

### ISSUE THREAD

**Issue by nickveliki** [davidahouse/junit-to-md#13]
Hi, love what you've done here! Would you be willing to make a github action from this?

**Comment by nickveliki** [comment]
so since I was on sick leave, I went at it myself. Had to throw out libxmljs2 bc it was b***thing about not being able to run on node-20 actions with ncc and node-gyp couldn't build it with node-20

https://gitea.thern.wtf/actions/junit-to-md

it's still very basic, but it gets the job done

**Comment by davidahouse** [comment]
Thanks for taking this one on! And I hope you are ok and feeling better!
